name: install nix
description: installs nix and caches nix store binaries
runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@v9
      with:
        diagnostic-endpoint: ""
    - uses: DeterminateSystems/magic-nix-cache-action@v2
      with:
        diagnostic-endpoint: ""
