name: update flake lock
description: updates outdated dependencies in flake lock file
inputs:
  github-token:
    description: token used to verify against github when creating PRs
    required: true
  gpg-private-key:
    description: GPG key used to sign commits
    required: true
  gpg-passphrase:
    description: GPG signing key passphrase
    required: true
runs:
  using: composite
  steps:
    - uses: DeterminateSystems/update-flake-lock@v20
      with:
        token: ${{ inputs.github-token }}
        pr-title: "chore(flake): update flake.lock dependencies"
        pr-reviewers: patryk-szydlowski
        sign-commits: true
        gpg-private-key: ${{ inputs.gpg-private-key }}
        gpg-passphrase: ${{ inputs.gpg-passphrase }}
